language: julia
os:
  - osx
  - linux
julia:
  - 1.0
  - 1.1
  - 1.2
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
after_success:
  - julia -e 'VERSION >= v"0.7.0-DEV.5183" && using Pkg;
      VERSION >= v"0.7.0-DEV.5183" || cd(Pkg.dir("Wavelets"));
      Pkg.add("Coverage");
      using Coverage;
      Coveralls.submit(Coveralls.process_folder())'
